### ISSUE TITLE
Dashboard Admin

### ISSUE THREAD

**Issue by RhyneeAI** [nandamaull244/DAWALA#11]
Sesuaikan dengan desain di Figma (untuk datanya dummy dulu saja)

**Comment by nandamaull244** [comment]
![screencapture-127-0-0-1-8000-admin-akun-manajemen-verification-table-2024-10-22-17_05_03](https://github.com/user-attachments/assets/956d7034-6e9d-4dcf-a513-d713384f41ba)
done abangkuh
