### ISSUE TITLE
Revisi Menu Registrasi

### ISSUE THREAD

**Issue by nunuy1494** [nandamaull244/DAWALA#4]
![Screenshot 2024-10-15 19 22 10](https://github.com/user-attachments/assets/ab994195-8d44-4ce1-bf19-d19ef4bfba6e)
1. diganti (Perorangan/Untuk Diri Sendiri)
2. diganti (Lembaga/Instansi)

![Screenshot 2024-10-15 19 26 21](https://github.com/user-attachments/assets/ddf00aa1-cf0e-4514-b032-b8e540bf450a)
1. ada tambahan opsi Desa dan Lembaga
2. ada tambahan menu jika memilih RT, RW, Desa ( kolom pilihan kecamatan dan desa)

**Comment by nandamaull244** [comment]
![image](https://github.com/user-attachments/assets/3dfc9ed4-b916-42fc-9398-7da85e40ea2a)
done

**Comment by nunuy1494** [comment]
minta tolong saat user memilih yayasan, lembaga atau instansi, ada tambahkan kolom untuk diisi manual, menerangkan bahwa mereka dari yayasan/lembaga/instansi mana?
terus poin nomor 1 belum yaa nan?
yang tambahan opsi desa dan lembaga

**Comment by nandamaull244** [comment]
![image](https://github.com/user-attachments/assets/1973e737-44d6-4bf7-8c88-61b0d02636e7)
done
