### ISSUE TITLE
Revisi Menu Profil

### ISSUE THREAD

**Issue by nunuy1494** [nandamaull244/DAWALA#5]
buatkan satu page untuk menu "Profil" dengan isi konten meliputi:

section 1 Tentang Dawala
section 2 visi & misi
section 3 Tim Dawala

Saat di klik menu dropdown, hanya berpindah section bukan page.

Atau dibuatkan visual yang bagus menurut front-end developer

**Comment by nandamaull244** [comment]
done in branch landing-page
