### ISSUE TITLE
Tambah icon slider di statistik landing page

### ISSUE THREAD

**Issue by nunuy1494** [nandamaull244/DAWALA#6]
![Screenshot 2024-10-15 19 11 21](https://github.com/user-attachments/assets/a8785a54-513f-440d-9f08-0045cd5c4bf7)

tolong tambah icon slidernya, agar bisa slide manual

**Comment by nandamaull244** [comment]
![image](https://github.com/user-attachments/assets/09e09bfd-0dd4-43b7-9034-6dec6fd78376)
done
