### ISSUE TITLE
Tambah menu di navigasi bar

### ISSUE THREAD

**Issue by nunuy1494** [nandamaull244/DAWALA#7]
Tolong tambah menu "Layanan Cepat"

dengan deskripsi:
layanan cepat adalah layanan yang di khususkan untuk situasi tertentu, dengan kategori, sebagai berikut: 
1. kecelakaan
2. penduduk yang berhadapan dengan hukum
3. atau situasi urgensi lainnya

dibuat button "Call Center Darurat" (nama sementara)
CTA langsung menghubungi no whatsapp team dawala, dengan pesan teks template otomatis:
"Layanan Darurat Dawala-Peduli" (bersifat sementara)

**Comment by nandamaull244** [comment]
oke done
